# Generated by Django 4.2.20 on 2025-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="username"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("real_name", models.CharField(max_length=30, verbose_name="realname")),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="phonenumber"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "患者"),
                            ("doctor", "医生"),
                            ("admin", "管理员"),
                        ],
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="idcard",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="年龄"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "db_table": "User",
            },
        ),
    ]
