# Generated by Django 4.2.20 on 2025-05-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backends_proj", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="患者可以添加个人的健康情况和其他相关描述",
                        max_length=2000,
                        null=True,
                        verbose_name="个人描述",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, null=True, verbose_name="病史"),
                ),
                (
                    "allergies",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="过敏史"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="紧急联系人"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="紧急联系电话",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_info",
                        to="backends_proj.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "患者信息",
                "verbose_name_plural": "患者信息",
                "db_table": "patientinfo",
            },
        ),
    ]
