# Generated by Django 5.2.1 on 2025-05-24 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends_proj', '0002_patientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateTimeField(verbose_name='时间段')),
                ('total_quota', models.PositiveIntegerField(default=20, verbose_name='总号量')),
                ('remaining_quota', models.PositiveIntegerField(default=20, verbose_name='剩余号量')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_slots', to='backends_proj.user', verbose_name='医生')),
            ],
            options={
                'verbose_name': '号源',
                'verbose_name_plural': '号源',
                'db_table': 'appointment_slot',
            },
        ),
        migrations.CreateModel(
            name='RegistrationOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='挂号单号')),
                ('status', models.CharField(choices=[('pending', '待就诊'), ('completed', '已完成'), ('canceled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_orders', to='backends_proj.user', verbose_name='患者')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_orders', to='backends_proj.appointmentslot', verbose_name='号源')),
            ],
            options={
                'verbose_name': '挂号单',
                'verbose_name_plural': '挂号单',
                'db_table': 'registration_order',
            },
        ),
    ]
