# Generated by Django 5.2.1 on 2025-06-01 20:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends_proj', '0003_appointmentslot_registrationorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 21, 31, 35, 842921, tzinfo=datetime.timezone.utc), verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 20, 32, 31, 939564, tzinfo=datetime.timezone.utc), verbose_name='起始时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationorder',
            name='order_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='挂号单号'),
        ),
        migrations.AlterField(
            model_name='registrationorder',
            name='status',
            field=models.CharField(choices=[('pending', '待就诊'), ('completed', '已完成'), ('canceled', '已取消'), ('diagnosing', '正在就诊')], default='pending', max_length=10, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, help_text='医生的专业背景、擅长领域等介绍', max_length=2000, null=True, verbose_name='医生简介')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='backends_proj.user', verbose_name='医生')),
            ],
            options={
                'verbose_name': '医生简介',
                'verbose_name_plural': '医生简介',
                'db_table': 'doctor_profile',
            },
        ),
    ]
