# Generated by Django 5.2.1 on 2025-06-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends_proj', '0004_remove_appointmentslot_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(blank=True, help_text='医生所属科室', max_length=100, null=True, verbose_name='科室'),
        ),
    ]
