# Generated by Django 5.2.1 on 2025-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends_proj', '0005_doctorprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', '患者'), ('doctor', '医生'), ('admin', '管理员')], max_length=20, verbose_name='role'),
        ),
    ]
